name: RentTable
version: '${project.version}'
main: org.destplay.renttable.RentTable
api-version: '1.16'
commands:
  rent:
    description:     TestCom1
    usage: /<command>
  rent list:
    description:     Список моих аренд
    usage: /<command>
  rent all:
    description:     Список всех аренд для op
    usage: /<command>
  rent tp:
    description:     Список всех аренд для op
    usage: /<command> <regionname>